-- Test data for the CRBT21M -> CRBT16M synchronization tool.
-- Execute only on non-production databases after MAP_CP_RBT, TONELIST and RBT_LOG exist.
USE crbt21m;
INSERT INTO MAP_CP_RBT (TONE_CODE) VALUES ('SYNC_TEST_ACTION_1');
INSERT INTO TONELIST (TONE_CODE) VALUES ('SYNC_TEST_ACTION_1');
INSERT INTO MAP_CP_RBT (TONE_CODE) VALUES ('SYNC_TEST_ACTION_3');
INSERT INTO RBT_LOG (ID, TONE_CODE, ACTION_TYPE, RESULT)
VALUES (900000001, 'SYNC_TEST_ACTION_1', 1, 1),
       (900000002, 'SYNC_TEST_ACTION_3', 3, 1);
