-- Test schema and data for the CRBT21M -> CRBT16M synchronization tool.
-- Execute only on local/non-production databases.

CREATE DATABASE IF NOT EXISTS crbt21m;
CREATE DATABASE IF NOT EXISTS crbt16m;

CREATE TABLE IF NOT EXISTS crbt21m.MAP_CP_RBT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TONE_CODE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_MAP_CP_RBT_TONE_CODE (TONE_CODE)
);
CREATE TABLE IF NOT EXISTS crbt21m.TONELIST (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TONE_CODE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TONELIST_TONE_CODE (TONE_CODE)
);
CREATE TABLE IF NOT EXISTS crbt21m.RBT_LOG (
    ID BIGINT NOT NULL,
    TONE_ID BIGINT,
    TONE_CODE VARCHAR(100),
    ACTION_TYPE INT NOT NULL,
    RESULT INT NOT NULL,
    SERVER VARCHAR(50),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS crbt16m.MAP_CP_RBT LIKE crbt21m.MAP_CP_RBT;
CREATE TABLE IF NOT EXISTS crbt16m.TONELIST LIKE crbt21m.TONELIST;
CREATE TABLE IF NOT EXISTS crbt16m.RBT_LOG LIKE crbt21m.RBT_LOG;
CREATE TABLE IF NOT EXISTS crbt16m.TONELIST_SYNLOG (
    LOG_ID BIGINT NOT NULL AUTO_INCREMENT,
    TONE_ID BIGINT,
    TONE_CODE VARCHAR(100),
    MOD_DATE DATETIME NOT NULL,
    DESCRIPTION TEXT,
    STATE TINYINT NOT NULL,
    PRIMARY KEY (LOG_ID)
);

INSERT INTO crbt21m.MAP_CP_RBT (ID, TONE_CODE, DESCRIPTION)
VALUES (900000001, 'SYNC_TEST_ACTION_1', 'Test MAP_CP_RBT for ACTION_TYPE 1'),
       (900000002, 'SYNC_TEST_ACTION_3', 'Test MAP_CP_RBT for ACTION_TYPE 3')
ON DUPLICATE KEY UPDATE DESCRIPTION = VALUES(DESCRIPTION);

INSERT INTO crbt21m.TONELIST (ID, TONE_CODE, DESCRIPTION)
VALUES (900000001, 'SYNC_TEST_ACTION_1', 'Test TONELIST for ACTION_TYPE 1')
ON DUPLICATE KEY UPDATE DESCRIPTION = VALUES(DESCRIPTION);

INSERT INTO crbt21m.RBT_LOG (ID, TONE_ID, TONE_CODE, ACTION_TYPE, RESULT, SERVER)
VALUES (900000001, 900000001, 'SYNC_TEST_ACTION_1', 1, 1, '127.0.0.1'),
       (900000002, 900000002, 'SYNC_TEST_ACTION_3', 3, 1, '127.0.0.1')
ON DUPLICATE KEY UPDATE TONE_ID = VALUES(TONE_ID), TONE_CODE = VALUES(TONE_CODE),
                        ACTION_TYPE = VALUES(ACTION_TYPE), RESULT = VALUES(RESULT), SERVER = VALUES(SERVER);
